<?php
/**
 * Plugin Overviews.
 * @package Maps
 * @author Flipper Code <flippercode>
 **/
 $features = array(
'Ability to display location title, location category, location latitude, location longitude with location message in the infowindow.',
'Ability to Sort listing by location, category and address alphabetically in location listing.',
'Ability to display default Start and End location in directions tab.',
'Ability to display directions results in KM and MILES.',
'Ability to google maps styles from https://snazzymaps.com.',
'Better user experience on time of Choose Locations for maps.',
'Ability to use External Database or Sources to add markers on google maps using new filter wpgmp_marker_source',
'Ability to display Featured Image or Custom fields in the infowindow for geo tags using new filter wpgmp_geotags_content',
'Display Posts/Pages or Custom Post Types on google maps.',
'Create unlimited maps and display on posts/pages using shortcode or in sidebar using widget.',
'Add unlimited locations using an easy to use interface for Google Maps.',
'Customize marker image for each location separately or group wise. Choose from +500 readymade markers or pick your own image.',
'Display your map perfectly on all devices. Create 100% responsive maps effortlessly.',
'Add any number of Google maps on pages/posts/sidebars.',
'Export/Import Features using CSV/JSON/XML or EXCEL.',
'Ajax based Location Listing.',
'Searchable Location Listing.',
'Paginated Location Listing.',
'Locating Listing Placeholder.',
'Directions & Route Suggestion',
'Nearby locations based on user’s current location.',
'Display multiple coloured routes on google maps.',
'Display traffic real time conditions and overlays using Traffic Layers.',
'Add bicycle path information to your maps using the Bicycling Layer.',
'Display physical maps based on terrain information.',
'Display photos from Panoramio as a layer to your maps using the Panoramio Layer.',
'A Cross Browser Compatible plugin. Fully tested on IE8, IE9, IE10 and all major browsers',
'Enable visual refresh on any Google Map at a button’s click.',
'Fully Responsive. Tested on real devices.',
'Display one infowindow at a time.',
'Multi-lingual Supported.',
'Multisite Enabled and ability to activate it network wide.',
'Define overlays on Google maps via an easy to use interface',
'Design your own Google map skins easily. Turn ON/OFF roads, places, water area.',
'Enable marker clusters if you have too many locations. Just activate and the plugin will handle the rest. ',
'Display polygons on Google Maps with options to customize',
'Display polylines on Google Maps with several customizable options',
'Modify existing polygons/polylines by making locations draggable',
'Define KML Layers on Google Maps',
'Apply 45 Imagery view on Google Maps',
'Fusion Table Layers',
'Awesome Shortcodes to add unlimited locations by address or latitude and longitude.',
'An innovative Quick Locations feature to add locations quickly by click.',
'Hooks Supported to modify maps,locations,listing on fly. Integrate api’s using hooks to the map.',
'Display Road Map view. This is the default map type.',
'Display Google Earth satellite images on just one click.',
'Display maps in a blend of normal and satellite views.',
'Display physical maps based on terrain information.',
'Display Google Maps on sidebars using widget.',
'Apply awesome google maps design from snazzymaps.com with just copy and paste.',
'Setup POV Heading and POV Pitch of Street View to customize Street View output of a location.',
'Integrate GEOJSON in to google maps.',
'Customize Infowindow Contents with help of Placeholders',
'Load markers from external database or API sources with help of filters (Hooks).',
'Ability to display infowindow on mouse click on mouse hover.',
);
 $productInfo = array('productName' => __('WP Google Map Plugin',WPGMP_TEXT_DOMAIN),
                        'productSlug' => 'wp-google-map-plugin',
                        'productTagLine' => 'Display Google Maps in Pages, Posts, Sidebar or Custom Templates. Unlimited maps, locations and categories supported. It’s Responsive, Multi-Lingual and Multi-Site Supported.',
                        'productTextDomain' => WPGMP_TEXT_DOMAIN,
                        'productIconImage' => WPGMP_URL.'core/core-assets/images/wp-poet.png',
                        'productVersion' => WPGMP_VERSION,
                        'productImagePath' => WPGMP_URL.'core/core-assets/product-images/',
                        'productImageName' => '1.png',
                        'premiumFeatures' => $features,
                        'docURL' => 'http://www.flippercode.com/documentations/wp-google-map-gold/',
                        'demoURL' => 'http://www.flippercode.com/product/wp-google-map-pro/',
                        'productSaleURL' => 'https://codecanyon.net/item/advanced-google-maps-plugin-for-wordpress/5211638',
                        'is_premium' => 'false',
                        'have_premium' => 'true',
                        'productBanner' => 'https://image-cc.s3.envato.com/files/167643906/wordpress-google-maps-plugin.jpg'
    );

    $productOverviewObj = new Flippercode_Product_Overview($productInfo);
